services:
  - type: web
    name: gif-hold-helte-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: JWT_SECRET
        value: grenaa-if-super-secret-2026
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false
